# -*- coding: utf-8 -*-
"""texttospeech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pr0T79q99a8Vl9ByfWucPbbf7djitoqE
"""

!pip install -U pip
!pip install TTS

# Step 2: Import TTS
from TTS.api import TTS

# Step 3: Load model and convert text to speech
tts = TTS(model_name="tts_models/en/ljspeech/tacotron2-DDC", progress_bar=False)

text = "HYYYYY GILRS, WHATS UP, WHAT ARE YOU DOING RIGHT NOW!?"
output_path = "output.wav"
tts.tts_to_file(text=text, file_path=output_path)

# Step 4: Show download button
from IPython.display import Audio, FileLink
print("🔊 Click to listen or download:")
display(Audio("output.wav"))      # For playback in Colab
display(FileLink("output.wav"))   # For downloading the file

