# -*- coding: utf-8 -*-
"""TTS-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPyrt7XrrNCt1-0HmTgA8j0wyfniYVnW
"""

!pip install TTS

# Step 2: Import TTS
from TTS.api import TTS

# Step 3: Load model and convert text to speech
tts = TTS(model_name="tts_models/en/ljspeech/tacotron2-DDC", progress_bar=False)

text = "This is a test. Hello from Coqui TTS!"
output_path = "output.wav"
tts.tts_to_file(text=text, file_path=output_path)

# Step 4: Show download button
from IPython.display import Audio, FileLink
print("🔊 Click to listen or download:")
display(Audio("output.wav"))      # For playback in Colab
display(FileLink("output.wav"))   # For downloading the file