# -*- coding: utf-8 -*-
"""whisper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2pb46E6Y2Y8Lmxu7-EzfWbdI8I5gO9a
"""

!pip install -U openai-whisper
!sudo apt update && sudo apt install ffmpeg

from google.colab import files
uploaded = files.upload()

import whisper

model = whisper.load_model("base")  # you can also try "small", "medium", or "large"
result = model.transcribe("audiooo.ogg")
print(result["text"])

with open("transcript.txt", "w", encoding="utf-8") as f:
    f.write(result["text"])
files.download("transcript.txt")

!pip install -U googletrans==4.0.0-rc1   # lightweight, free, no API key

from google.colab import files
uploaded = files.upload()

!ffmpeg -i "04. Tranform - Scale.mp4" -vn -acodec pcm_s16le -ar 16000 -ac 1 audio.wav

import whisper

model = whisper.load_model("base")  # You can try "small" or "medium" too
result = model.transcribe("audio.wav", task="translate")  # Translate to English
english_text = result["text"]

print("English Transcription:")
print(english_text)

from googletrans import Translator
translator = Translator()
translated = translator.translate(english_text, dest='ur')  # Change 'ur' to 'ko', 'ps', etc.
urdu_text = translated.text
print(urdu_text)

!pip install -q gTTS

from gtts import gTTS
tts = gTTS(urdu_text, lang='ur')  # Make sure 'lang' matches your translation
tts.save("ur_audio.mp3")

!ffmpeg -i "04. Tranform - Scale.mp4" -i urdu_audio.mp3 -c:v copy -map 0:v:0 -map 1:a:0 -shortest output_video.mp4